<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64</Platforms>
    <AssemblyName>OptiMaxing.Diagnostics</AssemblyName>
    <RootNamespace>OptiMaxing.Diagnostics</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OptiMaxing.Core\OptiMaxing.Core.csproj" />
  </ItemGroup>

</Project>
